## Type labels
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: feature
  color: "a2eeef"
  description: New feature or request

- name: enhancement
  color: "84b6eb"
  description: Improvement to existing functionality

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

## Priority labels
- name: "priority: critical"
  color: "b60205"
  description: Must be fixed immediately

- name: "priority: high"
  color: "d93f0b"
  description: Important issue that needs attention soon

- name: "priority: medium"
  color: "fbca04"
  description: Normal priority

- name: "priority: low"
  color: "0e8a16"
  description: Nice to have, not urgent

## Component labels
- name: "component: api"
  color: "c5def5"
  description: REST API / FastAPI

- name: "component: browser"
  color: "c5def5"
  description: Playwright browser engine

- name: "component: ai-engine"
  color: "c5def5"
  description: Vertex AI / Gemini integration

- name: "component: pipeline"
  color: "c5def5"
  description: Extraction pipeline

- name: "component: schemas"
  color: "c5def5"
  description: JSON schemas

## Status labels
- name: stale
  color: "ededed"
  description: No recent activity

- name: pinned
  color: "006b75"
  description: Exempt from stale bot

- name: "wontfix"
  color: "ffffff"
  description: This will not be worked on

- name: duplicate
  color: "cfd3d7"
  description: This issue or PR already exists

## CI / Dependency labels
- name: dependencies
  color: "0366d6"
  description: Dependency updates

- name: python
  color: "3572A5"
  description: Python-related changes

- name: docker
  color: "0db7ed"
  description: Docker-related changes

- name: ci
  color: "e6e6e6"
  description: CI/CD pipeline changes

- name: security
  color: "ee0701"
  description: Security-related issue or fix
