name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Hermes? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Hermes does this affect?
      options:
        - API / Server
        - Browser Engine
        - AI Engine
        - Pipeline
        - Schemas
        - Web UI
        - CLI / DevOps
        - Documentation
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
